on:
  push:
    branches:
      - "master"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
    - name: Declare some variables
      id: vars
      run: |
        echo "::set-output name=coverage_txt::${RUNNER_TEMP}/coverage.txt"
    - name: Test Coverage (pkg)
      run: go test ./... -coverprofile=${{ steps.vars.outputs.coverage_txt }}
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        files: ${{ steps.vars.outputs.coverage_txt }}
    - name: Run GoReleaser
      if: contains(github.ref, 'tags/v')
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
